global:
route:
  receiver: Default
  group_by: ["alertname"]
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

  routes:
  - receiver: AlertaMongoDB
    match:
      team: mongodb

  - receiver: AlertaWebApi
    match:
      team: webapi