global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - alert.rules
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: pedelogo_api
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ["web:80"]
        labels:
          versao: 1.0.0
  - job_name: mongodb_exporter
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets: ["mongodb_exporter:9216"]

